---
title: "DOI Seed Need Survey Goals"
author: "Reed Benkendorf"
date: "2025-01-08"
output: html_document
---

The NISRC planning committee at the Chicago Botanic Garden is developing estimates for native seed need across the United States under two paradigms. 
The first paradigm is a business as usual approach to restoration, but where native species are used in lieu of non-native species to achieve similar restoration outcomes. 
The second paradigm is one where land managers estimate what they would feasibly need, to achieve land health standards or their current restoration goals and targets. 
These estimates are required to determine how much seed the agencies within the Department of Interior *should* purchase over an annual period to be able to perform restoration activities on the lands which they administer. 

Historic seed buy data are inconsistent with future contexts, and have limited, utility in predicting the demand for native seed.  
Accordingly expert knowledge on *how* they would have treated restoration scenarios, using their current knowledge, and given access to native seed are deemed pertinent to estimating native seed need. 
However, acquiring expert knowledge *across* the United States is difficult because there are few experts per region;  anecdotally only up to a couple dozen. 
As a consequence typical survey response rates of 1/3 to 1/2 of polled individuals would generally result in only a handful of experts across some very large - and heterogeneous - domains. 

Data are sought on the following topics:

1) What is the maximum slope they will apply drill seeding at?   
2) What proportion of areas greater than MS1 slope are hydroseeding, broadcast, and aerial seeding applied to? 
2b) What proportion of areas less than MS1 slope are drill, hydroseeding, broadcast, and aerial seeding applied to? 
3) What is the target total number of seeds per unit area for each of these four methods: aerial, hydro, broadcast, aerial? **realized, idealized**
4) What proportion of each seed mix applied to NLCD cover class X slope < 10 is composed of the following lifeforms: **realized, idealized** 
4b) Do the proportions of lifeforms applied at slopes > 10 generally differ? If so... 

5) XXX species, how much of the land you have treated in YYY Cover class **have you applied it to?** Does it vary with slope? 
5b) XXX species, how much of the land you have treated in YYY Cover class **would you have liked to apply it to?** Does it vary with slope? 

It is easy to collect data on the realized across multiple people, it is difficult to collect data on the idealized. 
For these reasons we will treat "meeting land health standards" as an idealized goal for the BLM, where not less than 1/4 of land are failing to meet this goal. 
