---
title: "Tabulate Terrestrial Areas by DOI Region"
author: "Reed Clark Benkendorf"
date: "2025-01-27"
output: pdf_document
---

To estimate the amount of native seed required by each Department of Interior (DOI) region via the simulations several constants are required. 
These constants largely reflect the amount of terrestrial area per DOI region, and how these surfaces are allocated between administrative agencies. 
These calculations are performed in this document these values are then utilized for all subsequent analyses and products. 

Here we calculate the following values,
1) The sum of terrestrial area administered by each DOI agency
2) The sum of terrestrial area administered in each DOI region  
3) The sum of terrestrial area administered by each DOI agency in each DOI region 
4) The sum of National Land Cover Data (NLCD) classes, on DOI agency administered land by DOI region
5) The sum of NLCD classes by each DOI agency by DOI region

```{r load libraries}
library(tidyverse)
library(terra)
library(sf)
```




# For terrestrial surface we use the GADM, which has excellent resolution for the CONUS coastlines, islands off Alaska, and the Pacific Islands. 
# However it also draws land ownership over the Great Lakes. 
# We will use Natural Earth data to remove this coverage. 

